---
# tasks file for grafana
- name: Add Grafana datasources configuration file
  template:
    src: datasources.yml.j2
    dest: /configs/datasources.yml
  vars:
    monitoring_ip: "{{ lookup('file', 'files/ec2_public_ip.txt') }}"

- name: Add Grafana dashboard configuration files
  copy:
    src: "{{ item }}"
    dest: /configs
  loop:
    - node-exporter-full.json
    - node-exporter-full.yaml

- name: Create Grafana container
  docker_container:
    name: "{{ container_name }}"
    image: grafana/grafana:latest
    recreate: yes
    networks:
      - name: "{{ network }}"
    ports:
      - "{{ container_port }}:3000"
    volumes:
      - /configs/node-exporter-full.json:/var/lib/grafana/dashboards/node-exporter-full.json
      - /configs/node-exporter-full.yaml:/etc/grafana/provisioning/dashboards/node-exporter-full.yaml
      - /configs/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    env:
      GF_SECURITY_ADMIN_USER: "{{ gf_security_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ gf_security_admin_password }}"
    restart: yes
    restart_policy: "{{ restart_policy }}"